#!/usr/bin/env bash

key_name="school"
key_bits=4096
passphrase="betty"

# Generate the private key
openssl genpkey -algorithm RSA -out "$key_name.key" -aes256 -pass "pass:$passphrase" -pkeyopt rsa_keygen_bits:$key_bits

# Extract the public key from the private key
openssl rsa -in "$key_name.key" -out "$key_name.pub" -passin "pass:$passphrase" -pubout

echo "RSA key pair generated successfully."
