#!/usr/bin/env bash

# Generate RSA key pair with ssh-keygen
ssh-keygen -t rsa -b 4096 -f school

# Add passphrase to the private key
openssl rsa -aes256 -in school -out school_encrypted -passout pass:betty

# Clean up the unencrypted private key
rm school

# Output success message
echo "RSA key pair created successfully."
